version: '3.7'

services:

  # redis db
  redis:
    container_name: redis
    image: redis:6-alpine

  # celery broker (rmq)
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_DASHBOARD_PORT}:${RABBITMQ_DASHBOARD_PORT}
      - ${RABBITMQ_METRICS_PORT}:${RABBITMQ_METRICS_PORT}

volumes:
  shared-volume:
