version: '3.7'

services:
  # main application
  fastapi:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: ${APP_NAME}
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_STORE_DB_INDEX}
    expose:
        - ${APP_PORT}
    volumes:
      - ${APP_DIR}:${APP_DOCKER_DIR}/app
      - shared-volume:${SHARED_VOLUME_PATH}
    command: gunicorn app.api:app --workers ${APP_WORKERS} --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${APP_PORT} 

  # celery app
  worker:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: celery worker --app=worker.celery_app
    volumes:
      - ${APP_DIR}/worker:${APP_DOCKER_DIR}/worker
      - ${APP_DIR}:${APP_DOCKER_DIR}/app
      - shared-volume:${SHARED_VOLUME_PATH}
    container_name: celery
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_STORE_DB_INDEX}
    depends_on:
      - fastapi
      - nginx
      - redis
      - rabbitmq

  # redis db
  redis:
    container_name: redis
    image: redis:6-alpine

  # flower dashboard for celery
  dashboard:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: flower --app=worker.celery_app --port=${FLOWER_CONTAINER_PORT} --broker=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    ports:
      - ${FLOWER_HOST_PORT}:${FLOWER_CONTAINER_PORT}
    volumes:
      - ${APP_DIR}/worker:${APP_DOCKER_DIR}/worker
    container_name: flower
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_STORE_DB_INDEX}
    depends_on:
      - fastapi
      - nginx
      - redis
      - worker
      - rabbitmq

  # celery broker (rmq)
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_DASHBOARD_PORT}:${RABBITMQ_DASHBOARD_PORT}
      - ${RABBITMQ_METRICS_PORT}:${RABBITMQ_METRICS_PORT}

  # nginx
  reverse-proxy:
      build: ./nginx
      container_name: reverse-proxy
      restart: always
      ports:
          - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}
      depends_on:
          - fastapi

volumes:
  shared-volume:
