# mkdocs.yml
site_name: Object Storage API

repo_url: https://github.com/KiLJ4EdeN/fastapi-taskqueue
repo_name: fastapi-taskqueue

theme:
  name: "material"

  icon:
    logo: simple/applenews
    repo: fontawesome/brands/gitlab

  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

nav:
  - Calculation Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md


# Syntax Highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pejsamadi
      name: Pejman on Twitter

    - icon: fontawesome/brands/github
      link: https://github.com/pejmans21
      name: Pejman on GitHub

copyright: Copyright &copy; 2022 - 2023 Pejmans21
